#!/usr/bin/env python3
"""Validate output generated by 播客内容模块拆解Skill."""

from __future__ import annotations

import re
import sys
from pathlib import Path

RECOMMENDATION_SECTIONS = [
    "一句话推荐",
    "为什么这篇内容值得听",
    "为什么这个作者或嘉宾值得听",
    "为什么现在值得听",
]

TYPE_FILE_RE = re.compile(r"^(\d{2})-(.+)\.md$")
REC_HEADING_RE = re.compile(r"^##\s+(.+?)\s*$", re.M)
POINT_RE = re.compile(r"^###\s+(\d+)\.\s+观点：\*\*(.+?)\*\*\s*$", re.M)
EXPANSION_LABEL_RE = re.compile(r"^\*\*(.+?)：\*\*\s*$", re.M)
LIST_ITEM_RE = re.compile(r"^\s*(\d+)\.\s+(.+?)\s*$", re.M)


def recommendation_content(text: str, section: str) -> str:
    pattern = re.compile(
        rf"^##\s+{re.escape(section)}\s*$\n+(.*?)(?=^##\s+|\Z)",
        re.M | re.S,
    )
    match = pattern.search(text)
    return match.group(1).strip() if match else ""


def numbered_items(text: str) -> list[str]:
    return [m.group(1).strip() for m in re.finditer(r"^\s*\d+\.\s+(.+?)\s*$", text, re.M)]


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python validate_output.py <output-folder>")
        return 2

    folder = Path(sys.argv[1]).expanduser().resolve()
    if not folder.is_dir():
        print(f"[FAIL] Output folder not found: {folder}")
        return 2

    errors: list[str] = []
    warnings: list[str] = []

    recommendation_file = folder / "00-推荐理由.md"
    if not recommendation_file.exists():
        errors.append("缺少 00-推荐理由.md")
    else:
        rec_text = recommendation_file.read_text(encoding="utf-8", errors="replace")
        if not re.search(r"^#\s+推荐理由\s*$", rec_text, re.M):
            errors.append("00-推荐理由.md：缺少一级标题“# 推荐理由”")

        headings = REC_HEADING_RE.findall(rec_text)
        if headings != RECOMMENDATION_SECTIONS:
            errors.append(
                f"00-推荐理由.md：二级模块顺序或数量错误。实际 {headings}"
            )

        one_liner = recommendation_content(rec_text, "一句话推荐")
        if not one_liner:
            errors.append("00-推荐理由.md：一句话推荐为空")
        elif len(re.sub(r"\s+", "", one_liner)) < 20:
            warnings.append("00-推荐理由.md：一句话推荐可能过短，传播力不足")

        for section in RECOMMENDATION_SECTIONS[1:]:
            content = recommendation_content(rec_text, section)
            items = numbered_items(content)
            if len(items) != 3:
                errors.append(
                    f"00-推荐理由.md：模块“{section}”必须恰好有3条，实际 {len(items)} 条"
                )

    overview_file = folder / "00-观点总览.md"
    if not overview_file.exists():
        errors.append("缺少 00-观点总览.md")
        overview_text = ""
    else:
        overview_text = overview_file.read_text(encoding="utf-8", errors="replace")
        if not re.search(r"^#\s+观点总览\s*$", overview_text, re.M):
            errors.append("00-观点总览.md：缺少一级标题“# 观点总览”")
        for required in ["原内容标题", "原始文件", "观点类型总数"]:
            if required not in overview_text:
                errors.append(f"00-观点总览.md：缺少字段“{required}”")
        if "## 一句话概括整篇内容" not in overview_text:
            errors.append("00-观点总览.md：缺少“一句话概括整篇内容”模块")
        if "## 观点类型目录" not in overview_text:
            errors.append("00-观点总览.md：缺少“观点类型目录”模块")
        if "00-推荐理由.md" not in overview_text:
            errors.append("00-观点总览.md：缺少推荐理由链接")

    type_files = []
    allowed_special = {"00-推荐理由.md", "00-观点总览.md"}
    for path in folder.glob("*.md"):
        if path.name in allowed_special:
            continue
        m = TYPE_FILE_RE.match(path.name)
        if not m:
            warnings.append(f"非标准 Markdown 文件名：{path.name}")
            continue
        type_files.append((int(m.group(1)), path))

    if not type_files:
        errors.append("没有找到任何“编号 + 观点类型名”的 Markdown 文件")

    type_files.sort(key=lambda item: item[0])
    actual_numbers = [n for n, _ in type_files]
    expected_numbers = list(range(1, len(type_files) + 1))
    if actual_numbers != expected_numbers:
        errors.append(
            f"观点类型编号不连续：实际 {actual_numbers}，期望 {expected_numbers}"
        )

    previous_point_number = 0
    seen_type_titles: set[str] = set()
    total_points = 0
    for _, path in type_files:
        text = path.read_text(encoding="utf-8", errors="replace")
        heading_match = re.search(r"^#\s+(.+)$", text, re.M)
        if not heading_match:
            errors.append(f"{path.name}：缺少一级标题")
        else:
            title = heading_match.group(1).strip()
            normalized = re.sub(r"^\d{2}\s+", "", title)
            if normalized in seen_type_titles:
                errors.append(f"{path.name}：观点类型标题重复：{normalized}")
            seen_type_titles.add(normalized)

        points = POINT_RE.findall(text)
        if not points:
            errors.append(f"{path.name}：没有找到任何分支观点")
            continue

        for idx, (point_no, point_title) in enumerate(points, start=1):
            point_number = int(point_no)
            total_points += 1
            if point_number != previous_point_number + 1:
                errors.append(
                    f"{path.name}：分支观点编号不连续，期望 {previous_point_number + 1}，实际 {point_number}"
                )
            previous_point_number = point_number
            if len(point_title.strip()) < 8:
                warnings.append(f"{path.name}：第 {point_number} 条观点金句可能过短")

            point_start = text.find(f"### {point_no}. 观点：**{point_title}**")
            next_match = re.search(rf"^###\s+{point_number + 1}\.\s+观点：", text[point_start:], re.M)
            point_end = point_start + next_match.start() if next_match else len(text)
            point_block = text[point_start:point_end]

            label_match = EXPANSION_LABEL_RE.search(point_block)
            if not label_match:
                errors.append(f"{path.name}：第 {point_number} 条缺少拓展标签")
                continue

            label = label_match.group(1).strip()
            if label == "为什么":
                errors.append(f"{path.name}：第 {point_number} 条仍在使用旧的“为什么”结构")

            after_label = point_block[label_match.end():]
            items = LIST_ITEM_RE.findall(after_label)
            if len(items) < 2:
                errors.append(f"{path.name}：第 {point_number} 条拓展点少于2条")
                continue
            if len(items) > 4:
                errors.append(f"{path.name}：第 {point_number} 条拓展点超过4条")

            for item_no, item_text in items:
                if len(re.sub(r"\s+", "", item_text)) < 12:
                    warnings.append(f"{path.name}：第 {point_number} 条拓展点 {item_no} 可能过短")

            combined = " ".join(item for _, item in items)
            if point_title.strip() in combined:
                warnings.append(f"{path.name}：第 {point_number} 条拓展可能在重复观点金句本身")

    if overview_text:
        declared = re.search(r"观点类型总数[：:]\s*(\d+)", overview_text)
        if declared and int(declared.group(1)) != len(type_files):
            errors.append(
                f"总览声明观点类型数 {declared.group(1)}，实际文件数 {len(type_files)}"
            )
        for _, path in type_files:
            if path.name not in overview_text:
                errors.append(f"总览中缺少链接：{path.name}")

    print(f"Output folder: {folder}")
    print(f"Type files: {len(type_files)}")
    print(f"Branch viewpoints: {total_points}")

    if len(type_files) < 3:
        warnings.append("观点类型文件可能偏少，请确认是否过度合并主题板块")
    if total_points < 20:
        warnings.append("分支观点总数低于20条，请确认长播客是否拆得过于保守")

    for warning in warnings:
        print(f"[WARN] {warning}")
    for error in errors:
        print(f"[FAIL] {error}")

    if errors:
        print(f"Validation failed: {len(errors)} error(s), {len(warnings)} warning(s).")
        return 1

    print(f"Validation passed: 0 errors, {len(warnings)} warning(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

