#!/usr/bin/env python3
"""Validate output generated by 播客爆款文案生成Skill."""

from __future__ import annotations

import re
import sys
from pathlib import Path


def table_headers(text: str) -> list[list[str]]:
    headers: list[list[str]] = []
    lines = text.splitlines()
    for index in range(len(lines) - 1):
        first = lines[index].strip()
        second = lines[index + 1].strip()
        if not (first.startswith("|") and first.endswith("|")):
            continue
        if not re.fullmatch(r"\|[\s:|-]+\|", second):
            continue
        headers.append([cell.strip() for cell in first.strip("|").split("|")])
    return headers


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python validate_output.py <output-markdown>")
        return 2

    path = Path(sys.argv[1]).expanduser().resolve()
    if not path.is_file():
        print(f"[FAIL] Output file not found: {path}")
        return 2

    text = path.read_text(encoding="utf-8", errors="replace")
    errors: list[str] = []

    if not re.search(r"^#\s+\S+", text, re.M):
        errors.append("缺少一级标题")
    if not re.search(r"^##\s+爆款开头复刻\s*$", text, re.M):
        errors.append("缺少“## 爆款开头复刻”")

    headings = re.findall(r"^##\s+主线方案\s+([123])\s*$", text, re.M)
    if headings != ["1", "2", "3"]:
        errors.append(f"主线方案必须按 1、2、3 连续输出，实际为 {headings}")

    headers = table_headers(text)
    opening_header = ["原文结构", "原文内容", "输出后内容"]
    mainline_header = ["序号", "逻辑关系", "选用观点", "对应来源"]
    if opening_header not in headers:
        errors.append("缺少标准爆款开头复刻三列表")
    if headers.count(mainline_header) != 3:
        errors.append(
            f"主线四列表必须恰好出现 3 次，实际 {headers.count(mainline_header)} 次"
        )

    for number in ("1", "2", "3"):
        block_match = re.search(
            rf"^##\s+主线方案\s+{number}\s*$([\s\S]*?)(?=^##\s+主线方案\s+|\Z)",
            text,
            re.M,
        )
        if not block_match:
            continue
        block = block_match.group(1)
        if not re.search(r"^###\s+主线\s*$", block, re.M):
            errors.append(f"主线方案 {number} 缺少“### 主线”")
        if not re.search(r"\[\[[^\]]+\]\]", block):
            errors.append(f"主线方案 {number} 缺少可追溯 Obsidian 来源链接")

    forbidden = ["正文结构映射总表", "完整整稿"]
    for phrase in forbidden:
        if phrase in text:
            errors.append(f"残留旧输出合同：{phrase}")

    for error in errors:
        print(f"[FAIL] {error}")
    if errors:
        print(f"Validation failed: {len(errors)} error(s).")
        return 1

    print(f"Validation passed: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
